-- SyDent — فحص هوية المحاسبة (قراءة فقط · آمن لإعادة التشغيل أي وقت)
-- يُشغَّل ليلياً بـCI (.github/workflows/finance-integrity.yml) ويدوياً من SQL Editor.
-- كل صف = بند × عدد المخالفات. الحالة السليمة = كل الأعداد صفر.
-- v263 (13 أيلول 2026): وُلد بعد أن كشف الفحص اليدوي دفعتين بلا توزيع لم يرَهما أي حارس.
with
t01 as (select 'splits_sum_ne_payment' k, count(*) n from (select p.id, p.amount, coalesce(sum(s.amount),0) sa, count(s.id) ns from ledger_payments p left join payment_splits s on s.payment_id=p.id group by p.id) x where ns>0 and abs(sa-amount)>0.005),
t02 as (select 'payment_without_splits', count(*) from ledger_payments p where p.amount>0 and not exists (select 1 from payment_splits s where s.payment_id=p.id)),
t03 as (select 'split_cur_ne_payment_cur', count(*) from payment_splits s join ledger_payments p on p.id=s.payment_id where coalesce(s.currency,'SYP')<>coalesce(p.currency,'SYP')),
t04 as (select 'split_cur_ne_session_cur', count(*) from payment_splits s join ledger_sessions ls on ls.id=s.session_id where coalesce(s.currency,'SYP')<>coalesce(ls.currency,'SYP')),
t05 as (select 'earned_split_on_planned', count(*) from payment_splits s join ledger_sessions ls on ls.id=s.session_id where s.is_unearned=false and ls.status='planned'),
t06 as (select 'earned_split_without_session', count(*) from payment_splits where is_unearned=false and session_id is null),
t07 as (select 'unearned_split_with_session', count(*) from payment_splits where is_unearned=true and session_id is not null),
t08 as (select 'orphan_split_payment', count(*) from payment_splits s left join ledger_payments p on p.id=s.payment_id where p.id is null),
t09 as (select 'session_overcovered', count(*) from (select ls.id, ls.cost, sum(s.amount) sa from ledger_sessions ls join payment_splits s on s.session_id=ls.id and s.is_unearned=false group by ls.id, ls.cost) x where sa - cost > 0.005),
t10 as (select 'split_patient_ne_payment_patient', count(*) from payment_splits s join ledger_payments p on p.id=s.payment_id where s.patient_id is distinct from p.patient_id or s.doctor_id is distinct from p.doctor_id),
t11 as (select 'split_patient_ne_session_patient', count(*) from payment_splits s join ledger_sessions ls on ls.id=s.session_id join ledger_payments p on p.id=s.payment_id where p.patient_id<>ls.patient_id),
t12 as (select 'split_provider_stale', count(*) from payment_splits s join ledger_sessions ls on ls.id=s.session_id where s.provider_id is distinct from ls.provider_id),
t13 as (select 'split_date_stale', count(*) from payment_splits s join ledger_payments p on p.id=s.payment_id where s.payment_date is distinct from p.date),
t14 as (select 'manual_flag_without_splits', count(*) from ledger_payments p where p.manual_allocation=true and not exists (select 1 from payment_splits s where s.payment_id=p.id)),
t15 as (select 'stale_unearned_with_uncovered_session', count(*) from (select distinct un.patient_id from (select patient_id, coalesce(currency,'SYP') cur, sum(amount) unearned from payment_splits where is_unearned=true group by 1,2) un join (select ls.patient_id, coalesce(ls.currency,'SYP') cur, ls.cost - coalesce((select sum(s.amount) from payment_splits s where s.session_id=ls.id and s.is_unearned=false),0) gap from ledger_sessions ls where ls.status='completed') cov on cov.patient_id=un.patient_id and cov.cur=un.cur where cov.gap>0.005 and un.unearned>0.005) x),
t16 as (select 'nonpositive_amounts', (select count(*) from ledger_payments where amount<=0)+(select count(*) from payment_splits where amount<0)+(select count(*) from ledger_sessions where cost<0)+(select count(*) from account_adjustments where amount<=0)+(select count(*) from expenses where amount<=0)+(select count(*) from provider_payouts where amount<=0)+(select count(*) from lab_payments where amount<=0)),
t17 as (select 'adjust_reduction_gt_completed', count(*) from (select a.patient_id, coalesce(a.currency,'SYP') cur, sum(a.amount) adj from account_adjustments a where kind in ('discount','write_off') group by 1,2) x join (select patient_id, coalesce(currency,'SYP') cur, sum(cost) c from ledger_sessions where status<>'planned' group by 1,2) y on y.patient_id=x.patient_id and y.cur=x.cur where adj>c+0.005),
t18 as (select 'null_currency_rows', (select count(*) from ledger_sessions where currency is null)+(select count(*) from ledger_payments where currency is null)+(select count(*) from payment_splits where currency is null)+(select count(*) from expenses where currency is null)+(select count(*) from provider_payouts where currency is null)+(select count(*) from lab_payments where currency is null)+(select count(*) from lab_orders where currency is null)+(select count(*) from account_adjustments where currency is null)+(select count(*) from payment_plans where currency is null)),
t19 as (select 'lab_payment_cur_ne_lab_orders', count(*) from lab_payments lp where lp.lab_id is not null and not exists (select 1 from lab_orders lo where lo.lab_id=lp.lab_id and coalesce(lo.currency,'SYP')=coalesce(lp.currency,'SYP'))),
t20 as (select 'lab_order_patient_ne_session_patient', count(*) from lab_orders lo join ledger_sessions ls on ls.id=lo.session_id where lo.patient_id<>ls.patient_id),
t21 as (select 'payout_orphan_provider', count(*) from provider_payouts po where po.provider_id is not null and not exists (select 1 from clinic_doctors d where d.id=po.provider_id) and not exists (select 1 from clinic_employees e where e.id=po.provider_id)),
t22 as (select 'cross_tenant_split', count(*) from payment_splits s join patients pt on pt.id=s.patient_id where pt.doctor_id<>s.doctor_id)
select * from t01 union all select * from t02 union all select * from t03 union all select * from t04 union all select * from t05 union all select * from t06 union all select * from t07 union all select * from t08 union all select * from t09 union all select * from t10 union all select * from t11 union all select * from t12 union all select * from t13 union all select * from t14 union all select * from t15 union all select * from t16 union all select * from t17 union all select * from t18 union all select * from t19 union all select * from t20 union all select * from t21 union all select * from t22;
